wip exposing Font_BRep
TODO:

use:
set(FREETYPE_INCLUDE_DIR_ft2build ${OCE_BUNDLE_ROOT_PATH}/include/freetype CACHE PATH "" FORCE)
 in CMakeList.txt
to include of OCE_Visualization package ( required by Font_BRep )

514 jelleferinga:build$ /usr/bin/g++   -DCSFDB -DHAVE_CONFIG_H -DOCC_CONVERT_SIGNALS -D_Font_EXPORTS -D_OCC64 -stdlib=libstdc++ -Os -DNDEBUG -fPIC -I/Users/jelleferinga/miniconda/envs/PyRAPID_QML/include/freetype2  -I/Users/jelleferinga/GIT/pythonocc-core -I/Users/jelleferinga/miniconda/envs/PyRAPID_QML/include/python2.7 -I/Users/jelleferinga/miniconda/envs/PyRAPID_QML/include/oce -I/Users/jelleferinga/GIT/pythonocc-core/src/Visualization    -o CMakeFiles/_Font.dir/Darwin/x86_64-MinSizeRel-64/FontPYTHON_wrap.cxx.o -c /Users/jelleferinga/GIT/pythonocc-core/build/Darwin/x86_64-MinSizeRel-64/FontPYTHON_wrap.cxx
/Users/jelleferinga/GIT/pythonocc-core/build/Darwin/x86_64-MinSizeRel-64/FontPYTHON_wrap.cxx:6984:33: error: 'operator new' is a
      private member of 'Standard_Transient'
      result = (Font_BRepFont *)new Font_BRepFont();
                                ^
/Users/jelleferinga/miniconda/envs/PyRAPID_QML/include/oce/Font_BRepFont.hxx:41:24: note: constrained by implicitly private
      inheritance here
class Font_BRepFont :  Font_FTFont
                       ^~~~~~~~~~~
/Users/jelleferinga/miniconda/envs/PyRAPID_QML/include/oce/Standard_Transient_proto.hxx:36:5: note: member is declared here
    DEFINE_STANDARD_ALLOC
    ^
/Users/jelleferinga/miniconda/envs/PyRAPID_QML/include/oce/Standard_DefineAlloc.hxx:57:9: note: expanded from macro
      'DEFINE_STANDARD_ALLOC'
  void* operator new (size_t theSize)                                  \
        ^
/Users/jelleferinga/GIT/pythonocc-core/build/Darwin/x86_64-MinSizeRel-64/FontPYTHON_wrap.cxx:7036:33: error: 'operator new' is a
      private member of 'Standard_Transient'
      result = (Font_BRepFont *)new Font_BRepFont((NCollection_String const &)*arg1,arg2);
                                ^
/Users/jelleferinga/miniconda/envs/PyRAPID_QML/include/oce/Font_BRepFont.hxx:41:24: note: constrained by implicitly private
      inheritance here
class Font_BRepFont :  Font_FTFont
                       ^~~~~~~~~~~
/Users/jelleferinga/miniconda/envs/PyRAPID_QML/include/oce/Standard_Transient_proto.hxx:36:5: note: member is declared here
    DEFINE_STANDARD_ALLOC
    ^
/Users/jelleferinga/miniconda/envs/PyRAPID_QML/include/oce/Standard_DefineAlloc.hxx:57:9: note: expanded from macro
      'DEFINE_STANDARD_ALLOC'
  void* operator new (size_t theSize)